cs130-w21/2

- Pathways/app/src/main/AndroidManifest.xml
- Pathways/app/src/main/java/com/example/pathways/MainActivity.java
- Pathways/app/src/main/java/com/example/pathways/TripView.java
- Pathways/app/src/main/res/layout/trip_view.xml
> Pressing add button now creates a new tripview activity

- Pathways/app/build.gradle
- Pathways/app/google-services.json
- Pathways/build.gradle
Added Firebase config file and added Firebase to build.gradle on app and project level.
> Enabled FireBase API

- Pathways/app/src/main/java/com/example/pathways/NoteView.java
- Pathways/app/src/main/res/layout/activity_note_view.xml
- Pathways/app/src/main/res/layout/note_in_list.xml
> Add Note List and Add Create Note Button

- Pathways/app/src/main/java/com/example/pathways/Location.java
- Pathways/app/src/main/java/com/example/pathways/LocationConverter.java
- Pathways/app/src/main/java/com/example/pathways/LocationsListAdapter.java
- Pathways/app/src/main/java/com/example/pathways/Trip.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/drawable/ic_baseline_remove_circle_outline_36.xml
- Pathways/app/src/main/res/layout/activity_trip_view.xml
- Pathways/app/src/main/res/layout/locations_list.xml
- Pathways/app/src/main/res/layout/locations_list_item.xml
> Locations list

- Pathways/app/build.gradle
- Pathways/app/src/main/AndroidManifest.xml
- Pathways/app/src/main/java/com/example/pathways/LoginActivity.java
- Pathways/app/src/main/res/layout/activity_login.xml
Added basic UI components for logging in.  TODO: Attach UI to database.
> LoginActivity UI

- Pathways/.idea/gradle.xml
- Pathways/app/build.gradle
- Pathways/app/src/main/java/com/example/pathways/Location.java
- Pathways/app/src/main/java/com/example/pathways/LocationConverter.java
- Pathways/app/src/main/java/com/example/pathways/LocationsListAdapter.java
- Pathways/app/src/main/java/com/example/pathways/Trip.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/drawable/shape_gradient_top_shadow.xml
- Pathways/app/src/main/res/layout/activity_trip_view.xml
> Simons branch

- Pathways/.idea/gradle.xml
- Pathways/app/build.gradle
- Pathways/app/src/main/java/com/example/pathways/AppDatabase.java
- Pathways/app/src/main/java/com/example/pathways/DatabaseSingleton.java
- Pathways/app/src/main/java/com/example/pathways/ListToStringConverter.java
- Pathways/app/src/main/java/com/example/pathways/Location.java
- Pathways/app/src/main/java/com/example/pathways/LoginActivity.java
- Pathways/app/src/main/java/com/example/pathways/MainActivity.java
- Pathways/app/src/main/java/com/example/pathways/Trip.java
- Pathways/app/src/main/java/com/example/pathways/TripDao.java
- Pathways/app/src/main/java/com/example/pathways/TripEntity.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/java/com/example/pathways/UserDao.java
- Pathways/app/src/main/java/com/example/pathways/UserEntity.java
> Added database functionality and ability to search for trips

- Pathways/app/src/main/java/com/example/pathways/LoginActivity.java
- Pathways/app/src/main/java/com/example/pathways/MainActivity.java
- Pathways/app/src/main/java/com/example/pathways/TripDao.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/java/com/example/pathways/UserDao.java
Changed database from observing livedata to just using threads for access.
Also popped the login activity from the backstack so pressing back leaves the app and you can only go back to it by logging out.
> Quality of life changes

- Pathways/app/src/main/java/com/example/pathways/MainActivity.java
- Pathways/app/src/main/java/com/example/pathways/NoteView.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/layout/activity_main.xml
- Pathways/app/src/main/res/layout/activity_trip_view.xml
- Pathways/app/src/main/res/values/dimens.xml
> Moved navigation buttons to TripView

- Pathways/app/build.gradle
- Pathways/app/src/main/AndroidManifest.xml
- Pathways/app/src/main/java/com/example/pathways/CreateNoteFragment.java
- Pathways/app/src/main/java/com/example/pathways/Note.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/NotesAdapter.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/layout/activity_note_view.xml
- Pathways/app/src/main/res/layout/fragment_create_note.xml
- Pathways/app/src/main/res/values/strings.xml
- Pathways/spotify-app-remote-release-0.7.1/build/.gitignore
Closes #54 and #6 
Includes refactor of NoteView -> NoteActivity per proper conventions
> Finish create note

- Pathways/app/src/main/java/com/example/pathways/SpotifyActivity.java
- Pathways/app/src/main/res/layout/activity_spotify.xml
- Pathways/app/src/main/res/layout/player.xml
- Pathways/app/src/main/res/layout/playlist_item.xml
Debounce the search query to reduce number of queries and fix various bugs.
Including:
Incorrect songs being added
Oversized UI elements
List going underneath other view
> Spotify Improvements

- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
>  Pass trip ID and location ID from TripViewActivity to NoteActivity

- Pathways/app/src/main/java/com/example/pathways/AppDatabase.java
- Pathways/app/src/main/java/com/example/pathways/ListToStringConverter.java
- Pathways/app/src/main/java/com/example/pathways/Note.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/NoteDao.java
- Pathways/app/src/main/java/com/example/pathways/NoteEntity.java
- Pathways/app/src/main/java/com/example/pathways/NotesAdapter.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
Created notes are now added to room database.  On initialization of the notes page, notes in database will show up.
> Created notes are now added to room database

- Pathways/app/src/main/java/com/example/pathways/CreateNoteFragment.java
- Pathways/app/src/main/java/com/example/pathways/EditNoteFragment.java
- Pathways/app/src/main/res/layout/edit_note_fragment.xml
created a dialog that pops up when a user selects to edit a note
> added edit note dialog

- Pathways/.idea/render.experimental.xml
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/ReadNoteFragment.java
- Pathways/app/src/main/res/layout/fragment_read_note.xml
> Add fragment for reading note

- Pathways/app/src/main/java/com/example/pathways/LocationsListAdapter.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/drawable/ic_baseline_add_a_photo_36.xml
- Pathways/app/src/main/res/drawable/ic_baseline_note_add_36.xml
- Pathways/app/src/main/res/layout/activity_note_view.xml
- Pathways/app/src/main/res/layout/locations_list_item.xml
> Add support for adding notes to individual locations.

- Pathways/app/src/main/java/com/example/pathways/EditNoteFragment.java
- Pathways/app/src/main/java/com/example/pathways/Note.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/ReadNoteFragment.java
Added delete button that will delete note from list
> Note control

- Pathways/app/src/main/java/com/example/pathways/EditNoteFragment.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
can edit note and save changes now
> edit button added

- Pathways/app/src/main/java/com/example/pathways/MainActivity.java
- Pathways/app/src/main/java/com/example/pathways/TripViewActivity.java
- Pathways/app/src/main/res/layout/locations_list.xml
Can now delete trips. Deleting trips removes the trip entity from the database and the trip id from the user entity's list of trip ids.
> Added ability to delete trips

- Pathways/app/src/main/java/com/example/pathways/EditNoteFragment.java
- Pathways/app/src/main/java/com/example/pathways/Note.java
- Pathways/app/src/main/java/com/example/pathways/NoteActivity.java
- Pathways/app/src/main/java/com/example/pathways/ReadNoteFragment.java
> Final Touches to Journal - now not only functions but works smoothly

- .travis.yml
- Pathways/app/build.gradle
This includes Travis Continuous Integration that only checks that the project successfully build under the gradle script
> Travis CI Initial Commit
